config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'twits/index'

  resources :twits
  
  root 'twits#index'

end

app/models/twit.rb
class Twit < ActiveRecord::Base
    belongs_to :user
    
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "block.png" 
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
 has_many :twits

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "profile.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :timeoutable,
         :authentication_keys => [:login]         
  
  attr_accessor :login
  
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end  
  
  validates :username,
  :presence => true,
  :uniqueness => {
    :case_sensitive => false
  } 
  
  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:avatar, :username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
  
  helper_method :resource_name, :resource, :devise_mapping, :resource_class

  
  
end

app/controllers/twits_controller.rb
class TwitsController < ApplicationController
  before_action :set_twit, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!


  # GET /twits
  # GET /twits.json
  def index
    @twits = Twit.order('id DESC').all
  end

  # GET /twits/1
  # GET /twits/1.json
  def show
  end

  # GET /twits/new
  def new
    @twit = Twit.new
  end

  # GET /twits/1/edit
  def edit
  end

  # POST /twits
  # POST /twits.json
  def create
    @twit = Twit.new(twit_params)
    @twit.user_id = current_user.id
    respond_to do |format|
      if @twit.save
        format.html { redirect_to twits_index_path, notice: 'Twit was successfully created.' }
        format.json { render :show, status: :created, location: @twit }
      else
        format.html { render :new }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twits/1
  # PATCH/PUT /twits/1.json
  def update
    respond_to do |format|
      if @twit.update(twit_params)
        format.html { redirect_to @twit, notice: 'Twit was successfully updated.' }
        format.json { render :show, status: :ok, location: @twit }
      else
        format.html { render :edit }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twits/1
  # DELETE /twits/1.json
  def destroy
    @twit.destroy
    respond_to do |format|
      format.html { redirect_to twits_url, notice: 'Twit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twit
      @twit = Twit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twit_params
      params.require(:twit).permit(:user_id, :body, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  
end

app/helpers/twits_helper.rb
module TwitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TWITING</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="mySidenav" class="sidenav">
  <span href="javascript:void(0)" class="glyphicon glyphicon-remove" onclick="closeNav()" id="close"></span>
   <% if user_signed_in? %>
     <%= image_tag current_user.avatar, id:"dpnav" %>
     <p id="dpname">@<%= current_user.username %></p>
     <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
     <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
   <% else %>
     <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
     <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
   <% end %>
</div>
 

 <div id="main">
    <%= yield %>
 </div>  


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/twits/_form.html.erb
<%= form_for @twit = Twit.new, html: { multipart: true } do |f| %>
  <% if @twit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twit.errors.count, "error") %> prohibited this twit from being saved:</h2>

      <ul>
      <% @twit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" >
    <%= f.label :image %><br />
    <%= f.file_field :image, autofocus: true %>
  </div>
  
  <div class="field" >
    <%= f.text_area :body, id:"text-area", maxlength: 140 %>
  </div>
  
  <div class="actions" id="submit">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/twits/_form2.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }, html: { multipart: true} ) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %><br />
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "off" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<%= link_to "Back", :back %>

app/views/twits/edit.html.erb
<h1>Editing Twit</h1>

<%= render 'form' %>

<%= link_to 'Show', @twit %> |
<%= link_to 'Back', twits_path %>

app/views/twits/index.html.erb
<div id="headbar">
  <nav class="navbar navbar-default" id="header">
    <div class="container-fluid">
      <span onclick="openNav()" ><%= image_tag current_user.avatar(:thumb), id:"nav"%></span>
      <span onclick="scrolltoTop()"><%= image_tag 'bird.png', class: 'image responsive',  id:"home" %></span>
      <span onclick="openNav2()" ><%= image_tag 'tweet.png', class: 'image responsive', id:"tweet" %></span>  
     </div>
  </nav>
</div>  

<p id="notice"><%= notice %></p>

<div id="mySidenav2" class="sidenav2">
  <span href="javascript:void(0)" class="glyphicon glyphicon-remove" onclick="closeNav2()" id="close2"></span>
     <h1 id="ntwit">New Twit</h1>
        <%= render 'form' %>
</div>

    <% @twits.each do |twit| %>
    <div class="panel panel-default">
      <div class="panel-body"> 
        <%= image_tag twit.user.avatar(:thumb), id:"dppost" %>
        <p id="postname">@<%= twit.user.username %></p>
        <p><%= twit.user.email %></p><br />
        <p id="post"><%= twit.body %></p>
        <p id="imagepost"><%= image_tag twit.image.url(:medium) %></p>
          <div class="btn-group">
            <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"  id="options">
              <span><%= image_tag 'options.png', class: 'image responsive', id:'optdot' %></span>
            </a>
            <ul class="dropdown-menu dropdown-menu-left" >
              <li><a><%= link_to 'Show', twit %></a></li>
                <% if twit.user.username == current_user.username %>
                  <li><a><%= link_to 'Destroy', twit, method: :delete, data: { confirm: 'Are you sure?' } %></a></li>
                <% end %>
             </ul>
          </div>
      </div>
    </div> 
    <% end %>

<br>

app/views/twits/new.html.erb
<div id="mySidenav2" class="sidenav2">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
     <h1>New Twit</h1>
        <%= render 'form' %>
        <%= link_to 'Back', twits_path %>
</div>

app/views/twits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @twit.user.username %>
</p>

<p>
  <strong>Body:</strong>
  <%= @twit.body %>
</p>

<%= link_to 'Edit', edit_twit_path(@twit) %> |
<%= link_to 'Back', twits_path %>